services:
  web:
    command: ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "6500"]
    # env_file:
    #   - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6500:6500"
    volumes:
      - .:/app
